require: rubocop-rails

AllCops:
  SuggestExtensions: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.1.4
  NewCops: enable

AllCops:
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'spec/fixtures/**/*'
    - 'config/puma.rb'
    - 'Guardfile'
    - 'scripts/**/*'
    - 'local/**/*'
    - 'spec/support/webmocks.rb'
    - 'config/environments/*'
    - 'lib/migrations/*'
    - '.irbrc'
    - 'config/initializers/*'
    - 'app/graphql/*'
    - 'app/controllers/users/*'

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
  AllowedMethods:
    - configure
    - context
    - describe
    - factory
    - FactoryBot.define
    - it
    - context
    - included

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Enabled: false

